import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="relative flex flex-col items-center justify-start bg-gradient-to-b from-[#064a44] to-[#1c0f0f]">
        <div className="opacity-55"></div>
        <div className="mx-auto flex h-dvh w-screen max-w-md flex-col overflow-hidden rounded-lg bg-gradient-to-br from-black to-neutral-900 font-mono tracking-tight shadow-xl ring-1 ring-white/10">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
